addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip, testbuild.zip]
    target_paths: 5213564d-1c50-491a-aa88-438c1b601a15
after_success: ['mvn clean cobertura:cobertura coveralls:report', ./df-build.sh]
jdk: [openjdk6, openjdk7, oraclejdk8]
language: java
sudo: false
# Modified by Insights Service at 2016-03-23 08:41:59.281144
