addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip]
    target_paths: c561f30e-4c2c-4b29-8889-757ddd538a74
after_success: ['mvn clean cobertura:cobertura coveralls:report', ./df-build.sh]
jdk: [openjdk6, openjdk7, oraclejdk8]
language: java
sudo: false
# Modified by Insights Service at 2016-02-23 13:32:31.717461
