addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip]
    target_paths: e8652d54-6e3d-48f9-9f86-48546277cfb1
after_success: ['mvn clean cobertura:cobertura coveralls:report', ./df-build.sh]
jdk: [openjdk6, openjdk7, oraclejdk8]
language: java
sudo: false
# Modified by Insights Service at 2016-03-02 11:47:46.362915
