addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip]
    target_paths: 348627a6-466a-4521-9296-4c633426a9fc
after_success: ['mvn clean cobertura:cobertura coveralls:report', ./df-build.sh]
jdk: [openjdk6, openjdk7, oraclejdk8]
language: java
sudo: false
# Modified by Insights Service at 2016-02-26 15:59:46.166343
