addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip]
    target_paths: d3c70d11-4bec-41ee-a9fb-d7bbd8a02f49
after_success: ['mvn clean cobertura:cobertura coveralls:report', ./df-build.sh]
jdk: [openjdk6, openjdk7, oraclejdk8]
language: java
sudo: false
# Modified by Insights Service at 2016-02-19 12:33:06.010698
