addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip]
    target_paths: 04c1f45d-ca7c-412a-8ce8-8c3277f01bac
after_success: ['mvn clean cobertura:cobertura coveralls:report', ./df-build.sh]
jdk: [openjdk6, openjdk7, oraclejdk8]
language: java
sudo: false
# Modified by Insights Service at 2016-02-22 12:36:02.343182
